### ISSUE TITLE
Issue dynamically adding cards to the bottom of the stack.

### ISSUE THREAD

**Issue by Sparkomatic** [ViCode/ng2-swipe-cards#20]
My this.cards array consists of 3 items on initialisation and on swiping once I'd like the top card to disappear and the second card to display (this currently appears to be happening already) but then I'd like to dynamically add a new item to the this.cards array, but that item go on the bottom of the pack, and not display until the two cards above it have displayed in turn. The intention is to always have 3 cards in the pack/stack.

I've tried different things like this.cards.pop(), this.cards.shift() and this.cards.unshift() and either the order messes up (often with the array order and display order not correlating with each other), or I end up with an increasingly incrementing cards array.
I believe this is to do with HTML order - nodes at the bottom of the tree appear on top of nodes earlier in the tree.
Is it possible to introduce a prepend function specifically for adding cards to the bottom of the pack.
Something like: 
parentNode.removeChild(element);
parentNode.insertBefore(element, parentNode.firstChild);

**Comment by ViCode** [comment]
Hi there,

On a swipe or emitting on the callLike parameter, the first value of the array will always be removed. 
If your goal is to keep 3 cards in the array you should push a new element to your array when the onLike event is thrown. This way you could have an infinite cycle and keep 3 elements permanently in your array.
