### ISSUE TITLE
Can't bind to 'orientation' since it isn't a known property of 'sc-card'.

### ISSUE THREAD

**Issue by ITServicesAM** [ViCode/ng2-swipe-cards#22]
Hey,

at first thanks for this lib. The plunker looks awesome!

I have a Problem in my Ionic2 App. I get the above error for all bindable properties of the sc-card component. Anyone else with this Problem? I have imorptet the Module in my NgModule...

Here my Version Infos:
Cordova CLI: 6.5.0
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.9.0
Xcode version: Not installed

**Comment by ViCode** [comment]
Hi there,

I have no idea what could could cause the error, but i invite you to take a look at the demo for ionic here : https://github.com/ViCode/ng2-swipe-cards-ionic-demo
It could may be help you solving your problem.
