### ISSUE TITLE
Remove BrowserModule from component imports

### ISSUE THREAD

**Issue by chrillewoodz** [ViCode/ng2-swipe-cards#24]
This causes my app to break since I've already included BrowserModule on my own. And I'm positive most people will have done the same.

**Comment by chrillewoodz** [comment]
Check out my pull request, I haven't tested it but it should work just fine :)

**Comment by chrillewoodz** [comment]
I made a new pull request with the required changes.

**Comment by ViCode** [comment]
Hi there,

Thanks for the fix.
It is indeed a problem, i did test your fix and it seems to work.
I will patch it soon.
