### ISSUE TITLE
Swiping really quickly causes middle/bottom card to be swiped instead of the top card

### ISSUE THREAD

**Issue by chrillewoodz** [ViCode/ng2-swipe-cards#27]
https://embed.plnkr.co/ebTZz51SsYUs7wzLemuo/ go here and just swipe really quickly a few times and then start swiping slowly and you will see the issue.

**Comment by ViCode** [comment]
Are you swiping from a mobile phone or a web browser? I could not reproduce it.
May be i should think about a way to immobilize the bottom cards when the front one is not totally swiped yet.

**Comment by chrillewoodz** [comment]
Web browser, Chrome to be specific.

**Comment by chrillewoodz** [comment]
Actually I forgot to mention that you need to swipe quickly a few times and then use the buttons. Seems to be able to reproduce it easier that way.

**Comment by ViCode** [comment]
Ok i did reproduced it with the button clicked. I will take a look at it.

**Comment by chrillewoodz** [comment]
Great :)

**Comment by ViCode** [comment]
Fixed in 1.0.15
