### ISSUE TITLE
Failed to load ~@angular/material

### ISSUE THREAD

**Issue by AlessandroSchneiderSignUP** [ViCode/ng2-swipe-cards#3]
Hi there,

importing SwipeCardsModule in app.module.ts I get the following error:

`zone.js:1382 GET http://localhost:4200/~@angular/material/core/theming/prebuilt/deeppurple-amber.css 404 (Not Found)

zone.js:388 Unhandled Promise rejection: Failed to load ~@angular/material/core/theming/prebuilt/deeppurple-amber.css ; Zone: <root> ; Task: Promise.then ; Value: Failed to load ~@angular/material/core/theming/prebuilt/deeppurple-amber.css undefined

zone.js:390 Error: Uncaught (in promise): Failed to load ~@angular/material/core/theming/prebuilt/deeppurple-amber.css(…)`

Any idea? before it has thrown an error reclaiming that there is no cards.css...

Thanks !

**Comment by ViCode** [comment]
Hi there!

Thanks for the report. It seems indeed to be a problem with the css load in the npm packages.
I did a fix on the version 1.0.6, the css will now be included inside the components and not in separate files. Everything should be work now.

Hope it did fix your problem.
