### ISSUE TITLE
Failed to load card.css

### ISSUE THREAD

**Issue by XPanniX** [ViCode/ng2-swipe-cards#4]
Hello there,

I'm trying to get your package to work with Ionic 2 Framework (JS App Framework).  
When running my app now it's looking for a `card.css` file in the root directory which can't be found.  
Since there are some more files injected on the app build process I don't have access to the root directory and therefore can't create a card.css file.   
But what I'm wondering about is that neither in the demo nor in the docu it requires this card.css file.

I hope you can tell me what I'm doing wrong.

**Comment by ViCode** [comment]
Hi there!

Thanks for the report. It seems indeed to be a problem with the css load in the npm packages.
I did a fix on the version 1.0.6, the css will now be included inside the components and not in separate files. Everything should be work now.

Hope it did fix your problem.
